# api_gateway_config.yaml
swagger: '2.0'
info:
  title: main
  description: API for backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /api/v1/{protocol}/{quote}:
    post:
      summary: Get a quotation
      operationId: routing
      consumes:
        - application/json
      produces:
        - application/json
      parameters: [
        {name: protocol, in: path, description: protocol, required: true, type: string},
        {name: quote, in: path, description: quotes, required: true, type: string}
      ]
      x-google-backend:
        address: http://gw-main.swp-private-dns.com:8000/
        path_translation: CONSTANT_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string